#!/bin/bash
#

while getopts ":v:" opt; do
  case $opt in
    v)
      if [ "$OPTARG" == "master" ]; then
        cp package.json build-package.json
      else
        sed -e "s%\"react-native\": \".*\"%\"react-native\": \"${OPTARG}\"%g" package.json > build-package.json
      fi
      docker build -t packager:$OPTARG .
      rm build-package.json
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
