#!/bin/bash
#

while getopts ":v:" opt; do
  case $opt in
    v)
      sed -e 's/\"react-native\": \".*\"/\"react-native\": \"0.4.4\"/g' package.json > build-package.json
      docker build -t packager:$OPTARG .
      rm build-package.json
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
